### ISSUE TITLE
Implement From trait between Address and String

### ISSUE THREAD

**Issue by manuelmauro** [manuelmauro/algonaut#3]
Currently `Address` has two methods doing exact this. Implementing the trait `From` in both directions may improve the struct's ergonomics.

**Comment by i-schuetz** [comment]
Hi! I'm considering working on this. There are several possibilities and wanted to clarify first:
(not super experienced with Rust, apologize for possible oversights)

- `TryFrom` trait (since it can fail): this seems to require a bit awkward syntax when passing `String`, e.g: 

```rust
Address::from_str(&*gen_response.address)
// or
(&*gen_response.address).try_into()
```

- `FromStr` trait:
```rust
Address::from_str(&gen_response.address)
// or
gen_response.address.parse::<Address>()?
```
To convert to string, we'd to implement the `ToString` trait.

**Comment by manuelmauro** [comment]
Hi @i-schuetz ! I was thinking of this issue just yesterday, thanks for the analysis! In fact my doubt was the requirement for perfect conversion of the `From` trait and your solutions perfectly address the issue. I would go with the first option because I think that we will be using it especially with string slices and because the `try_into` feels cleaner than `parse::<Address>`. In theory we could implement both, but I think that is better to keep a single way of doing things whenever possible.  What do you think?

**Comment by i-schuetz** [comment]
With `parse` actually we don't have to set the type, unless type inference doesn't work (which happens only in 2 places at the moment). Given this, I'm slightly in favor of it, as "parse" sounds a bit more accurate (and we don't need the `&* syntax, which we'd need with `TryInto`, also in 2 places). I'll open the PR with this. Can change it.
